apiVersion: v1
kind: ConfigMap
metadata:
  name: model-bundle-source
  namespace: secure-ai-poc
data:
  BUNDLE_REPOSITORY: j0ssGZ/confidential-model-delivery-artifacts
  BUNDLE_REVISION: c6d037b94a2f9e1072198a9c8de94540ada55edc
